#!/bin/sh

set -eu

cd "$(dirname $0)/.."

if [ $(id -u) -eq 0 ]; then
	PRIVS=nobody:nogroup

	find data -type d -print0 | xargs -r -0 chmod 777
	find data -type f -print0 | xargs -r -0 chmod 666
fi

exec 2>&1
exec chpst -e "$(dirname $0)/env" ${PRIVS:+-u $PRIVS} npm start
